paths:

  /api/products:

    get:
      summary: Obtiene todos los productos
      tags: 
        - Products
      responses:
        "200":
          description: Los productos se obtuvieron satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor

    post:
      summary: Crea un nuevo producto
      tags: 
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct'
      responses:
        "200":
          description: El producto se creo satisfactoriamente
        "401":
          description: Error de autorización (no posee permisos adecuados)
        "500":
          description: Error interno del servidor

  /api/products/{pid}:

    get:
      summary: Obtiene un producto por Id
      tags: 
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del producto que se desea solicitar
        schema:
          $type: String
      responses:
        "200":
          description: Se obtuvo el producto satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor

    put:
      summary: Actualiza un producto a partir de su Id
      tags: 
        - Products
      # security:
      #   - bearerAuth: [] # De components
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del producto que se desea actualizar
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        "200":
          description: Se actualizo el producto satisfactoriamente
        "401":
          description: Error de autorización (no posee permisos adecuados)
        "500":
          description: Error interno del servidor

    delete:
      summary: Elimina un producto a partir de su Id
      tags: 
        - Products
      # security:
      #   - bearerAuth: [] # De components
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del producto que se desea eliminar
        schema:
          $type: String
      responses:
        "200":
          description: Se elimino el producto satisfactoriamente
        "401":
          description: Error de autorización (no posee permisos adecuados)
        "500":
          description: Error interno del servidor

  /api/products/mockingproducts:

    get:
      summary: Obtiene productos falsos, por defecto trae 100
      tags: 
        - Products
      parameters:
      - name: quantity
        in: query
        required: false
        description: Cantidad de productos simulados que se desean obtener
        schema:
          $type: String
      responses:
        "200":
          description: Se obtuvo el producto satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor

components:

  schemas:

    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado por mongo
        title:
          type: String
          description: Título del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto, en pesos argentinos
        thumbnails:
          Type: Array
          description: Imágenes del producto
        code:
          type: Number
          description: Código del producto (único)
        stock:
          type: Number
          description: Stock del producto
        status:
          type: Boolean
          description: Estado del producto (true para habilitados, y false para productos deshabilitados)
        owner:
          type: String
          description: Email del creador del producto ("admin" en caso de que sean creados por el administrador)
      example:
        _id: ObjectId(65bf2577eb4489fe2f045df3)
        title: Termo eléctrico
        description: Producto hecho en Argentina, la tapa se usa como mate, dos modos de temperatura
        price: 50000
        thumbnails: [imagenTermo.jpg]
        code: 5
        stock: 798
        status: true
        owner: admin

  requestBodies:

    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnails:
          Type: array
          description: Imágenes del producto
        code:
          type: number
          description: Código del producto (único)
        stock:
          type: number
          description: Stock del producto
        status:
          type: boolean
          description: Estado del producto
        owner:
          type: string
          description: Email del creador del producto ("admin" en caso de que sean creados por el administrador)

    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnails:
          Type: array
          description: Imágenes del producto
        code:
          type: number
          description: Código del producto (único)
        stock:
          type: number
          description: Stock del producto
        status:
          type: boolean
          description: Estado del producto